# -*- coding: utf-8 -*-
"""Assignment-6_Data-Generation-using-Modelling-and-Simulation-for-ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vApvuoruZVQt-l0jvUP_qYy7BfCTgmxf
"""

# ===============================
# 1. Install and Import Libraries
# ===============================
!pip install cantera

import cantera as ct
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

# For reproducibility
np.random.seed(42)

print("Cantera Version:", ct.__version__)


# ===============================
# 2. Load Chemical Mechanism
# ===============================
gas = ct.Solution("gri30.yaml")

print("\n--- Simulator Information ---")
print(f"Number of species: {gas.n_species}")
print(f"Number of reactions: {gas.n_reactions}")
print("Sample species:", gas.species_names[:5])


# ===============================
# 3. Default State
# ===============================
gas.TP = 300, ct.one_atm

print("\n--- Default State ---")
print("Temperature (K):", gas.T)
print("Pressure (Pa):", gas.P)


# ===============================
# 4. Reaction of Interest (NH3)
# ===============================
nh3_index = gas.species_index("NH3")

print("\n--- Reaction Output Parameter ---")
print("NH3 species index:", nh3_index)
print("NH3 production rate at default state:",
      gas.net_production_rates[nh3_index])


# ===============================
# 5. Parameter Bounds
# ===============================
TEMP_MIN, TEMP_MAX = -40, 40      # Celsius
PRESS_MIN, PRESS_MAX = 10, 50     # atm

print("\n--- Parameter Bounds ---")
print(f"Temperature (°C): {TEMP_MIN} to {TEMP_MAX}")
print(f"Pressure (atm): {PRESS_MIN} to {PRESS_MAX}")


# ===============================
# 6. Generate Simulation Data
# ===============================
records = []

for _ in range(1000):
    T_c = np.random.uniform(TEMP_MIN, TEMP_MAX)
    P_atm = np.random.uniform(PRESS_MIN, PRESS_MAX)

    T_k = T_c + 273.15
    gas.TP = T_k, P_atm * ct.one_atm

    rate = abs(gas.net_production_rates[nh3_index])
    records.append([T_c, P_atm, rate])

df = pd.DataFrame(
    records,
    columns=["Temperature_C", "Pressure_atm", "Reaction_Rate"]
)

print("\n--- Sample Dataset ---")
print(df.head())


# ===============================
# 7. Save Dataset
# ===============================
df.to_csv("cantera_simulated_data.csv", index=False)
print("\nDataset saved as cantera_simulated_data.csv")


# ===============================
# 8. Machine Learning Models
# ===============================
X = df[["Temperature_C", "Pressure_atm"]]
y = df["Reaction_Rate"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling (important for SVR & KNN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Support Vector Regression": SVR(),
    "KNN": KNeighborsRegressor()
}

results = []

for name, model in models.items():
    if name in ["Support Vector Regression", "KNN"]:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append([name, mse, r2])

results_df = pd.DataFrame(
    results, columns=["Model", "MSE", "R2 Score"]
)

print("\n--- Model Performance ---")
print(results_df)